### ISSUE TITLE
AttributeError next_update during infer:1074

### ISSUE THREAD

**Issue by dare0021** [shedskin/shedskin#243] opened 2017-10-23 10:09 UTC
Appears to be caused by a behavior change in progressbar

Fixed by adding as line 1072: gx.progressbar.start() within the if gx.progressbar is None: context

**Comment by Arkanosis** [comment] 2017-10-23 10:13
Thanks for the report!

I'm not 100% sure of myself, but I think I've had a similar problem in the past because I was using `progressbar` instead of `progressbar2`. Shedsdkin depends on `progressbar2` as specified in the `requirements.txt`. Could you please confirm that's the version you're using?

If that's the cause, we probably should make it more obvious, or support both dependencies, if possible.

Thanks again :)

**Comment by dare0021** [comment] 2017-10-24 03:50
You're right, that's what happened.
The extra line was unnecessary after installing progressbar2.

I tested with and without the extra line, and it seems to run fine with it as well, so it's your call, I guess.
The extra line means compatibility with progressbar1, but that means you might be limited to not using new features in progressbar2 in the future.

For the requirements.txt file, I don't see how that could hurt. There could be a single line in the installation directions that says "check the requirements.txt file".
Not that that would completely prevent  idiots like me from messing up :)

**Comment by srepmub** [comment] 2019-02-18 10:23
this should be fixed in the meantime, as I ran into the same issue the other day.

**Closed by srepmub** 2019-02-18 10:23 UTC
